export const ADD_PLACE = 'ADD_PLACE';
export const DELETE_PLACE = 'DELETE_PLACE';

export const NET_REGISTER_BEGIN = 'NET_REGISTER_BEGIN'
export const NET_REGISTER_SUCCESS = 'NET_REGISTER_SUCCESS'
export const NET_REGISTER_FAIL = 'NET_REGISTER_FAIL'

export const NET_LOGIN_BEGIN = 'NET_LOGIN_BEGIN'
export const NET_LOGIN_SUCCESS = 'NET_LOGIN_SUCCESS'
export const NET_LOGIN_FAIL = 'NET_LOGIN_FAIL'

export const NET_GET_USER_INFO = 'NET_GET_USER_INFO'